[package]
name = "dev-syn/rbx-typewriter"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
    "**/*.spec.lua",
    "testRunner.client.lua",
    "build"
]

[dependencies]
GoodSignal = "stravant/goodsignal@0.2.1"
[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"